name: Release

on:
  push:
    tags: [ '**' ]

permissions:
  contents: read

jobs:
  ubuntu:
    uses: 9506hqwy/actions/.github/workflows/rust-release-ubuntu.yml@main

  release:

    needs: [ubuntu]

    permissions:
      contents: write

    uses: 9506hqwy/actions/.github/workflows/common-create-release.yml@main
    with:
      title-prefix: v
